### ISSUE TITLE
circular import when import graphite_api

### ISSUE THREAD

**Issue by liyichao** [vimeo/graphite-influxdb#41] opened 2015-02-11 04:09 UTC
\>>>import graphite_influxdb

Traceback (most recent call last):
  File "graphite_api/app.py", line 63, in <module>
    configure(app)
  File "graphite_api/config.py", line 127, in configure
    finders.append(load_by_path(finder)(config))
  File "graphite_api/config.py", line 74, in load_by_path
    return getattr(finder, klass)
AttributeError: 'module' object has no attribute 'InfluxdbFinder'

**Comment by ChristianKniep** [comment] 2015-04-16 12:14
Got the same error.... any idea so far?

**Comment by pkittenis** [comment] 2015-07-03 10:09
Duplicate of #34  - was fixed with PR #39 which was added to master at `https://github.com/vimeo/graphite-influxdb/commit/0bff4a6e2371ee676d2086e089e86ba2229067d5`

**Comment by pkittenis** [comment] 2015-07-14 16:02
Take that back - it's been re-introduced in master.

**Closed** 2015-08-12 15:11 UTC
